spring.application.name=SafeTagAPIV2

# Active le regroupement des requêtes SQL
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
# Optionnel : voir les statistiques de batch (pour debug au début)
spring.jpa.properties.hibernate.generate_statistics=false

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/safetag_rpps
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-className=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
